// import Head from 'next/head'
// import Image from 'next/image'
import { NavbarDefault, NavbarProfile } from "../components/navbar"
import Footer from "../components/Footer"
import Layout from "../components/General"
import HomeBanner from "../components/HomeBanner"
import ListProduct from "../components/ListProduct"

export default function Home() {
  return (
    <Layout>
      {/* <Head>
        <title>SecondHand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <HomeBanner/>
      <ListProduct/>
    </Layout>
  )
}
