// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../components/General"
import HomeBanner from "../components/HomeBanner"
import ListProduct from "../components/ListProduct"

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>SecondHand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Layout>
        <HomeBanner/>
        <ListProduct/>
      </Layout>
    </div>
  )
}
